name: darc
services:
  orchestrator:
    restart: always
    hostname: orchestrator
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      # - "9229:9229"
      - "8080:8080"
      - "54545:54545" # caluse auth endpoint
      - name: main
        target: 5196
        app_protocol: http
        # host_ip: 127.0.0.1
        published: "5196"
        mode: host # or ingress for load balanced
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: sync
          path: ./
          target: /workspace/
          ignore:
            - "**/.git/**"
            - "**/.jj/**"
            - "**/node_modules/**"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - git-sync:/shared/git-sync
      - ./.git-local:/shared/git-local
      ## check how to share the claude .claude.json file or if store in .claude/...
      - claude-home:/root/.claude
      - code-server-data:/root/.local/share/code-server/User
      - ./stacks:/workspace/stacks

volumes:
  git-sync: {}
  claude-home: {}
  code-server-data: {}
  
# TODO:--security-opt apparmor=docker-default docker/compose
# rootless docker
# gvisor
# Open Policy Agent (OPA) for Docker
# Falco for runtime security monitoring
# Docker Bench Security for auditing
